# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  lint-test:

    runs-on: ubuntu-latest

    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV
        id: nvm

      - name: Use Node.js ${{ env.NVMRC }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}

      - name: Instaling dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Lint code
        uses: borales/actions-yarn@v4
        with:
          cmd: run lint:code --quiet

      - name: Lint style
        uses: borales/actions-yarn@v4
        with:
          cmd: run lint:style --quiet

      - name: Testing
        uses: borales/actions-yarn@v4
        with:
          cmd: run test --silent

      - name: Start docs smoke test
        uses: borales/actions-yarn@v4
        with:
          cmd: run start:docs --smoke-test --quiet

      - name: Build project
        uses: borales/actions-yarn@v4
        with:
          cmd: run build

      - name: Generate component dry run
        uses: borales/actions-yarn@v4
        with:
          cmd: run generate:component Foo --dry-run